### ISSUE TITLE
Register patient vaccination in ISIN

### ISSUE THREAD

**Issue by kubantjan** [mild-blue/covid-vaxx#113]
In endpoint that vaccinates patient add functionality that registers patient to ISIN

**Comment by tomaskourim** [comment]
Info:
Apidoc https://apidoc.uzis.cz/index.html
(potrebuje certifikát SÚKL (eRecept) nebo certifikát ÚZIS vydaný pro poskytovatele zdravotních služeb]

K tomu komentar https://www.uzis.cz/res/file/covid/covid-19-ockovani-datove-rozhrani-v-3-0.pdf. Maji testovaci prostredi, ktere funguje uplne bez loginu. S tim muzeme zacit.

Případě nejasností můžete kontaktovat naši metodickou podporu:
 https://www.uzis.cz/index.php?pg=aktuality&aid=8431
