### ISSUE TITLE
Add button to vaccinate

### ISSUE THREAD

**Issue by kubantjan** [mild-blue/covid-vaxx#119]
Button that is in patient detail in admin section.

AFter one presses it show pop up are you sure?

If yes tell endpoint that given patient was vaccinated.

Od backend add such enpoint. In DB store info whether patient was vaccinated or not as extra column in db (with time and null if not)

**Comment by LukasForst** [comment]
backend vyresen v #125

**Comment by thangout** [comment]
![image](https://user-images.githubusercontent.com/11322384/111192727-ac3c2980-85b9-11eb-9cfb-c681fc56c597.png)
![image](https://user-images.githubusercontent.com/11322384/111192797-c0802680-85b9-11eb-8dab-7e9afda48427.png)
