### ISSUE TITLE
Better explanation of required format

### ISSUE THREAD

**Issue by LukasForst** [mild-blue/covid-vaxx#128]
* v soucasne chvili je ten text docela maly a starsi lidi ho budou mit problem precist (nebo si ho vubec vsimnout)
* je treba zvetsit text (mozna vsude na strance, prece jen tam mame docela dost mista)
* mozna prijit s nejakym lepsim zpusobem, jak ukazovat ten "spravny format" daneho policka
* mozna pridat napovedu nekam, kde bude i priklad vyplnenych policek

**Comment by tomaskourim** [comment]
Pokazde, kdyz se nejake policko obarvi cervene, tak se vedle ukaze okenko s nejakym textem (ten pripadne dodam).

![image](https://user-images.githubusercontent.com/50045455/111606116-2e556980-87d7-11eb-98ff-60c1a4676712.png)

Texty a obecne ten formular zvetsit, optimalizoval bych na FullHD rozliseni.
