### ISSUE TITLE
Smarter format handling in the form on FE

### ISSUE THREAD

**Issue by LukasForst** [mild-blue/covid-vaxx#129]
* trimovat vsechno co se da
* dovolit zadani tel cisla s mezerama jako `xxx yyy` a ty pak smazat
* dovolit zadani rodneho cisla jak s `/` tak bez ni, pripadne i s `-` (nicmene musi byt na "spravnem" miste tzn `yyyyy/xxxy` je ok, ale `xx/xxxxxxxx` ok neni

**Comment by marazt** [comment]
Telefonni cislo input: https://www.npmjs.com/package/ngx-intl-tel-input
