### ISSUE TITLE
Data validation on backend

### ISSUE THREAD

**Issue by LukasForst** [mild-blue/covid-vaxx#13]
* validate all inputs on backend

**Comment by LukasForst** [comment]
co mi tak napada, ze je nutne validovat - to same co na FE + odpoved na vsechny otazky

- [ ] rodne cislo
- [ ] telefonni cislo
- [ ] email (pokud to umime nejak rychle, obecne to moc nejde)
- [ ] zodpovezeni vsech otazek
- [ ] souhlas se zpracovanim udaju/vakcinaci (ten se neuklada do databaze, ale musi se zkontrolovat - pokud bude nejaky false tak nic neulozit)

**Comment by marazt** [comment]
Otazky nezvalidujes ~ muzou byt true/false

**Comment by LukasForst** [comment]
@marazt myslel jsem spis zdali jsou vsechny zodpovezeny -- aka prislo ti `registration.answers.size() == database.questions.size()`
