### ISSUE TITLE
Handle http 409 on FE

### ISSUE THREAD

**Issue by LukasForst** [mild-blue/covid-vaxx#131]
* pokud se clovek pokusi registrovat se stejnym personal number tak BE vrati status code 409 s message `Entity already exists!.`
* je treba tohle na FE odchytit pri registraci a pokud to nastane, tak zobrazit nejakou hlasku ve stylu "myslime si, ze jste se uz pokusil jednou registrovat , pokud potrebujete opravit svoji registrace napiste na nasledujici emailovou adresu "support@mild.blue""
* podobnou hlasku je treba zobrazovat na te posledni strance po registraci - znovu ve stylu, pokud vidite nejakou chybu, nebo chcete zmenit registraci kontaktujte support@mild.blue

**Comment by kubantjan** [comment]
jen bych dal jiny email, at to mame oddelene. vaccination@mild.blue mi prijde lepsi. A to mozna by mel byt i ten email ze kteryho to budeme posilat ne (dokud neprijde pozadavek na neco jinyho od uradu)

**Comment by LukasForst** [comment]
Může být, ale měl by být v češtině (tzn třeba ockovani@mild.blue, nebo tak nějak) - přece jen je to pro českou populaci hlavně

**Comment by kubantjan** [comment]
@LukasForst  no ale pak i produkce ale by mela byt ockovani.mild.blue asi nejlip ne? at jsme konsitentni mejl + webovka.

**Comment by LukasForst** [comment]
Jo, to souhlasím, jako napsat vaccination není úplně lehké 😀

**Comment by LukasForst** [comment]
@kubantjan tak uz BE bezi i na https://ockovani.mild.blue (stejne tak https://vaccination.mild.blue/ zustava a zustane online)

**Comment by tomaskourim** [comment]
ockovani@mild.blue mi prijde fajn, stejne jako web ockovani.mild.blue
