### ISSUE TITLE
Fix 500 returned, when 400 should be returned instead

### ISSUE THREAD

**Issue by kubantjan** [mild-blue/covid-vaxx#139]
Fix tests added in #140 that have todo of this issue

**Comment by LukasForst** [comment]
co vidim `docker logs be | jq 'select(.exception != null)'`

* 825d5f29-c01a-45b2-923f-b9fb7a21398d - `com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException`
* acaf661d-53e5-4dcc-935c-20ab15de3608 - `com.fasterxml.jackson.databind.exc.InvalidFormatException`
* 8e0010e1-6c24-4027-aadb-d8a9ffa07c68 - `com.fasterxml.jackson.databind.exc.MismatchedInputException`
* e000a9d1-4dc9-4b9a-91a7-bc5456e2efe0 - `com.fasterxml.jackson.databind.exc.InvalidFormatException`
* 717839bd-e35a-4496-af3c-f2d670980bc3 - `com.fasterxml.jackson.databind.exc.MismatchedInputException`
