### ISSUE TITLE
Cookies banner

### ISSUE THREAD

**Issue by LukasForst** [mild-blue/covid-vaxx#148]
* captcha uklada nejaka cookies, je tedy) treba pridat banner, ze tahle stranka pouziva cookies
![image](https://user-images.githubusercontent.com/14038818/111130169-2eefc500-8577-11eb-883d-bf8ac42fb933.png)
![image](https://user-images.githubusercontent.com/14038818/111130211-39aa5a00-8577-11eb-96a7-306ee565239f.png)
https://developers.google.com/recaptcha/docs/faq#does-recaptcha-use-cookies

asi cc @tomaskourim

**Comment by kubantjan** [comment]
@LukasForst  

podle tohohle https://www.iubenda.com/en/help/23902-google-recaptcha-gdpr-how-to-be-compliant

potrebujeme banner.

**Comment by kubantjan** [comment]
to je asi na @thangout  nebo @misslecter  a rekl bych, ze must have

**Comment by LukasForst** [comment]
Ok, tak je třeba to formulovat pak tak, že to je skutečně jenom kvůli ověření, že jsou to lidi a ne boti.

**Comment by tomaskourim** [comment]
@misslecter prosim, ta textace je nejaka standardni nebo to je na me to dodat?

**Comment by misslecter** [comment]
@tomaskourim není standardní, ale stačí nám nějaká jedna věta :)
