### ISSUE TITLE
Improve frontend performance and refactor home component

### ISSUE THREAD

**Issue by misslecter** [mild-blue/covid-vaxx#159]
- [ ] Merge Answer and Question interfaces
- [ ] Use same form components for editing patient info as used in administration
- [ ] Improve performance (fix slow click for checkboxes and toggle buttons, cut down the number of component rendering)
- [ ] Fix questions rendering as described in #157

**Comment by LukasForst** [comment]
tady bych zminil ze by bylo fajn se kouknout i na komenty #152 konkretne na https://github.com/mild-blue/covid-vaxx/pull/152#issuecomment-800396930 a pripadne se pak dohodnout jaka data se budou skutecne posilat z BE tak, aby to FE vyhovovalo a co nejmene jsme zatezovali databazi
