### ISSUE TITLE
Revert colors health questionaire

### ISSUE THREAD

**Issue by tomaskourim** [mild-blue/covid-vaxx#166]
Zobrazeni dotazniku naopak. `Ne` je v nasem pripade zelene, `Ano` cervene:
![image](https://user-images.githubusercontent.com/50045455/111468752-31dce800-8726-11eb-9f54-9b0a2dbc240a.png)

**Comment by LukasForst** [comment]
+ bych taky byl proto, aby ty barevne ctverecky byly stejne velke (ted je ano zelene vetsi, nez ne cervene)
