### ISSUE TITLE
Add information during login

### ISSUE THREAD

**Issue by kubantjan** [mild-blue/covid-vaxx#168]
Add information to login alongside username and password:
- doctor name
- nurse name
- series number (cislo sarze)
- expiration date (te dane vakciny, nemeni se stejne jako cislo sarze - respektive oboje se meni vyjimecne)

Add those boxes to when login under username and password:

- doctor name
- nurse name
- series number (cislo sarze)
- expiration date 

save to backend alongside the login token so when vaccination button is pressed, this info can be saved there.

**Comment by LukasForst** [comment]
@tomaskourim, @kubantjan 

dve moznosti implementace:
1. proper verze, kdy mame v databazi tabulku dokotoru - email + heslo - a seznam sester, kazdy doktor ma svoje heslo se kterym se v prvnim kroku zaloguje, v dalsim vybere ze seznamu sester (nebo napise, ale bude to pripravenej set) a zada ockovaci latku
2. bude jedno master heslo pro doktory, ktere napise, nasledne do free textu napise doktor a pak dalsiho sestra and that's it

jednicka je samozrejme vyrazne casove narocnejsi jak na implementaci, tak na zavedeni do praxe (vytvoreni uzivatelskych uctu pro jednotlive doktory a pridani seznamu sester) -- nicmene bude to vyrazne bezpecnejsi a vsecno bude skutecne prolinkovane pres ids v databazi

dvojka je naopak skutecne jednoducha na implementaci a odpadne problem s pridavani uctu a sester -- problem nicmene je, ze to bude pekelne nekonzistentni -> jednou zada "Žára", pak "Zara" a jsou to dva jini lide a my nemame jak to overit, stejne tak u sester a nedejboze u kombinaci, navic se tyhle data znovu budou ukladat ve freetextu v databazi

osobne bych samozrejme sel cestou 1., ale je to vetsi voser a bojim se, ze by se stejne pak mohlo sklouznout na cestu 2., takze je to vas call

co se tyce implementace toho, kdo co udelal, tak backend tyhle data ulozi do tokenu, kterej chodi s kazdym requestem

**Comment by kubantjan** [comment]
@tomaskourim  ty veci doktor,sestra jsou jen pro zapamatovani do databaze, nebo se i posilaji do ISINU? maji nejaky presne dany format? Je tam potreba mit treba nejaky cislo doktora nebo tak? Pak by davala smysl 1. Jinak 2.

**Comment by tomaskourim** [comment]
Ještě zjišťují isin. Zatím bych připravil ten be, tedy abychom u očkování měli uloženo doktora a sestru. Pravděpodobně nakonec půjdeme nejsou cestou 1.5, tedy například 1 login ale tabulka doktorů v DB, že které si vybere

**Comment by LukasForst** [comment]
mame na tohle update? @tomaskourim 

porad chceme jit cestou jeden login per klinika?

**Comment by tomaskourim** [comment]
Update na to nemame
