### ISSUE TITLE
Frontend - Step 2 validation

### ISSUE THREAD

**Issue by marazt** [mild-blue/covid-vaxx#17]
Validate that all form options `Yes/No` are marked, otherwise do not allow to go to next step.

File `app.component.html:77` - `<!-- TODO: Validace, ze je vse zaskrtnute ANO/NE -->`

**Comment by misslecter** [comment]
Po diskuzi s @kubantjan necháme uživatele proklikávat se mezi kroky a přidáme poznámku k tlačítku `Odeslat požadavek`, že se pro odeslání musí uvést všechny informace a zaškrtnout souhlasy. Je to ok @marazt?

**Comment by marazt** [comment]
No ale tim padem by jsi mu na posledni strance (krok 3) mela rict: Nejde ti to odeslat, protoze:
- v kroku 1 ti chybi email
- v kroku 1 mas spatne zadane cislo
- v kroku dva nemas zaskrtnuto, jestli jsi tehotna nebo ne
- ...

Protoze kdyz budes mit konecnou validaci jen v poslednim kroku, budou z toho lidi zmateni (lidi jsou hloupi).

**Comment by misslecter** [comment]
Myslela jsem, že to bude jasné z těch žlutých `Neuvedeno` a tím, že řeknem, že vše má být uvedeno. 
Takhle v kroku 2 mu budem muset vyjmenovat vše jak říkáš, proč ho nepouštíme do kroku 3 😅
