### ISSUE TITLE
Doctor and receptionist roles

### ISSUE THREAD

**Issue by kubantjan** [mild-blue/covid-vaxx#170]
- doctor can call vaccinated endpoint and can see validate form button.

**Comment by LukasForst** [comment]
na BE pridat roli a rozdelit endpoint update patient na dva - vaccinate (role ADMIN/DOCTOR) - a update patient

**Comment by kubantjan** [comment]
@LukasForst  pckej vaccinate endpoint mame stejne preci ne? tadyto je jen o pravech na volani endpointu a ukazovani/neukazovani na FE>

**Comment by LukasForst** [comment]
jenze ten endpoint je obecnej pro update jakekoliv property pacienta (tzn jak questions, tak name, tak i prave vakcinace), tedy bude treba to splitnout, protoze na update ma prava kdekdo, ale na vakcinaci pouze doktor

**Comment by LukasForst** [comment]
tak to nejde na BE osetrit, protoze FE neposila changeset, ale celou entitu, a protoze sestra muze delat update, tak neni mozne osetrit to, aby nemohla zmenit vakcinaci (resp mozne to samozrejme je, ale pitome by se to delalo, tzn osetrime pouze na FE)

**Comment by tomaskourim** [comment]
@LukasForst  takze tohle je na @misslecter a na BE se nebude nic menit? Nicmene BE by mohl pripravit alespon ty 2 role dobrovolnik/doktor, ne?

**Comment by martin-majlis** [comment]
> tak to nejde na BE osetrit, protoze FE neposila changeset, ale celou entitu, a protoze sestra muze delat update, tak neni mozne osetrit to, aby nemohla zmenit vakcinaci (resp mozne to samozrejme je, ale pitome by se to delalo, tzn osetrime pouze na FE)

Validace urcite musi byt na backendu.

**Comment by tomaskourim** [comment]
@LukasForst tohle to podle me resi https://github.com/mild-blue/covid-vaxx/pull/298
