### ISSUE TITLE
Show nicer message when no patient found

### ISSUE THREAD

**Issue by tomaskourim** [mild-blue/covid-vaxx#172]
![image](https://user-images.githubusercontent.com/50045455/111609409-8b065380-87da-11eb-900a-829d2338c037.png)

Tohle je takove strohe. Dal bych tam zprávu ve stejném formátu jako když se potvrdí očkování. A ideálně i přidat tlačítko "Přidat pacienta"

**Comment by LukasForst** [comment]
souvisi se #48 

jsem proto to nedelat jako malej banner ale normalne velkej popup, takhle hrozi, ze si toho nikdo nevsimne + navic u popupu by melo vzdy byt "pripadne kontaktujte podporu na ockovani@mild.blue" a nekde to callId

**Comment by LukasForst** [comment]
![image](https://user-images.githubusercontent.com/14038818/111816137-c6894680-88dc-11eb-832c-2f0e3901a7c4.png)

closed tady #178
