### ISSUE TITLE
Dont persist search history across accounts

### ISSUE THREAD

**Issue by tomaskourim** [mild-blue/covid-vaxx#174]
Je fajn ukládat posledních 5 vyhledávaných rodných čísel. Ale když se odhlásím a přihlásím za jiného uživatele, tak je pořád vidím. To spíš nechceme (leda že by je viděl i doktor poté, co vyhledával admin pracovník, ale předpokládám, že to je v prohlížeči).

![image](https://user-images.githubusercontent.com/50045455/111610410-a02fb200-87db-11eb-9602-fff59a91ce57.png)

**Comment by LukasForst** [comment]
no to urcite necchceme, @misslecter po odhlaseni, nebo po te, co BE nekdy vrati 401 se **musi** promazat cela local i session storage
