### ISSUE TITLE
Dont show user not found

### ISSUE THREAD

**Issue by tomaskourim** [mild-blue/covid-vaxx#203]
![image](https://user-images.githubusercontent.com/50045455/114353824-c132bb00-9b6d-11eb-9380-05f33dd349cb.png)

Tohle potencialne poradi. At nenajdeme uživatele nebo heslo, chceme prostě vždycky napsat Špatné přihlašovací údaje, zkuste to prosím znovu.

**Comment by LukasForst** [comment]
Backend vrací vždy stejnou 401, tzn tohle je textace na FE.

**Comment by tomaskourim** [comment]
vsak to má label Frontend :)
