### ISSUE TITLE
Save data to DB

### ISSUE THREAD

**Issue by tomaskourim** [mild-blue/covid-vaxx#204]
Poznámka u očkování se nepropíše, do DB se uloží jen prázdný string

![image](https://user-images.githubusercontent.com/50045455/114356310-bc233b00-9b70-11eb-9d00-66669634a665.png)

Stejně tak u potvrzení správnosti
![image](https://user-images.githubusercontent.com/50045455/114356551-099fa800-9b71-11eb-8b97-a4da51939938.png)

Vaccinated at bych ukládal včetně hodiny (teď to je jen na dny)
![image](https://user-images.githubusercontent.com/50045455/114356383-d0673800-9b70-11eb-8383-207f6311eccf.png)

**Comment by LukasForst** [comment]
BE je ok, je na to test v #254 pokud se to stale deje, tak je to FE
