### ISSUE TITLE
Generate time when the patient should come

### ISSUE THREAD

**Issue by kubantjan** [mild-blue/covid-vaxx#210]

**Comment by tomaskourim** [comment]
Ke kazdemu ockovacimu mistu budeme mit oteviraci dobu od-do, delku slotu (asi 30min a asi bude spolecna pro vsechny mistnosti) a kapacitu slotu (podle poctu lekaru na miste, v nekterych skolach muze byt vice ockovacich mistnosti). 

Oteviraci dobu rozdelime na sloty (dle delek), kazdy slot bude mit informaci od-do, celkovou kapacitu a volnou kapacitu. Sloty seradime podle casu zacatku a postupne s registracemi budeme prirazovat lidi do jednotlivych slotu. Jakmile zaplnime kapacitu slotu, zacneme pridelovat dalsi slot.

Jakmile budou obsazene vsechny sloty, dane ockovaci misto zneaktivnime a nebudeme ho jiz lidem nabizet k registraci.
