### ISSUE TITLE
Select vaccination spot

### ISSUE THREAD

**Issue by kubantjan** [mild-blue/covid-vaxx#211]

**Comment by martin-majlis** [comment]
To represent this information we need several entities:

* **Location**
  * represents location where it is possible to be vaccinated 
  * attributes: `id`, `name`, `address`, `note`, `url`, ...
* **LocationAvailability**
  * represents when it is possible to get vaccinated
  * when the location is available and how long it may take could depend on the amount of available personell
  * attributes: `id`, `ts_open`, `ts_close`, `duration`, `location_id`.
* **VaccinationSlot**
  * represents vaccination slot
  * links to all involved entities - patient, medical stuff, vaccination, location availability
  * attributes: `id`, `ts`, `note`, all the linked entities mentioned above

Some of these entities - `Location` and `LocationAvailability` - could be hardcoded at the beginning and later on replaced with CRUD UI.

Does this makes sense? @tomaskourim

**Comment by tomaskourim** [comment]
I would it a bit simpler as we do not have to keep track about neither medical personnel nor location availability -> both is fixed. 3 tables should be enough
* Location (`id`, `name`, `address`, `capacity`, `note` should be enough)
* VaccinationSlot (`id`, `time_from`, `time_until`, `is_available`, (`order`), `location_id`)
* * This table will be filled once when we know the exact schedule and capacity of all Locations. When registering, patient will be assigned with proper VaccinationSlot
* PatientVaccinationSlot (`id`, `patient_id`, `vaccination_slot_id`)

And yes, it can be hardcoded for now.

**Comment by tomaskourim** [comment]
@martin-majlis Vidim PR. Je tohle tedy jasne?

**Comment by tomaskourim** [comment]
Nakonec mame jen 1 misto. Na BE by toto melo byt vice mene hotove, tak to nechme v te podobe, ze tam je 1 misto jako default (ale teoreticky jich muze byt vic). Tohle jako issue zaviram.
