### ISSUE TITLE
When validation fails on backend, show some nice info popup

### ISSUE THREAD

**Issue by kubantjan** [mild-blue/covid-vaxx#223]
TEn rika at si zvalidujes rodny cislo jmeno a rc cislo, ze to nesedi, pokud jsi si na 100% jisty, ze je spravne, tak at nam napises email

**Comment by tomaskourim** [comment]
Hodne souvisi s https://github.com/mild-blue/covid-vaxx/issues/127

Poslednim krokem je odeslani dat z FE na BE. BE je zvaliduje a vraci OK nebo error, ten se zobrazi na FE. Error muze byt i z ISIN. Chteli bychom dat info ve stylu:

Nedari se nam validovat vas pres ISIN. Pokud si jste fakt jisty, ze mate vsechno spravne, napiste mail. 

Problem s tim je, ze nam budou furt psat maily. Alternativne to tam dat nemusime. S tim je problem, ze ISIN fakt nefunguje a muze se to stat, ze proste cloveka nenajde. Idealni neco mezi je, ze treba ISIN zkusime 3x a teprve pak mu nabidneme moznost s mailem. Tady je problem, ze to asi neni uplne trivialni.

Zatim bych tohle vyresil tak, ze proste zobrazime error hlasku z ISINu.
