### ISSUE TITLE
Zaplatit mailjet

### ISSUE THREAD

**Issue by kubantjan** [mild-blue/covid-vaxx#224]
mame tam nejaky omezeny mesicni limit, co nam ted nebude stacit

**Comment by tomaskourim** [comment]
![image](https://user-images.githubusercontent.com/50045455/120620278-1c41a980-c45d-11eb-81bc-be7ee4f876f7.png)

Jestli ti prijde faktura na mail, tak ji prosim uloz do slozky pro Miru
