### ISSUE TITLE
Fill in vaccinaction spot table with some available times

### ISSUE THREAD

**Issue by kubantjan** [mild-blue/covid-vaxx#226]

**Comment by tomaskourim** [comment]
Tohle je spis na @LukasForst v ramci te BE funkcionality. Proste by to melo byt tak, ze k mistnosti nastavis od-do, delku slotu a pocet mist k slotu a pak se to bude uz pridavat automaticky. Manualne by mely nastavovat pouze mistnosti a ta bude jenom 1.
