### ISSUE TITLE
Time around interval

### ISSUE THREAD

**Issue by tomaskourim** [mild-blue/covid-vaxx#243]
Dnes zobrazime, ze se pacient ma dostavit 15:14-15:17. To vypada dementne, tak bych k zacatku a konci vzdy pridal 10 minut, aby to byl pulhodinovy interval. Idealne toto tedy 15:04-15:27, pripadne kdyby to bylo tezke, tak proste jak to pujde -> aby pacient dostal vetsi interval.

**Comment by LukasForst** [comment]
0 na zacatku, na konci pridat 15 a zaokrouhlit na cele minuty
