### ISSUE TITLE
Use better implementation for slots booking

### ISSUE THREAD

**Issue by LukasForst** [mild-blue/covid-vaxx#267]
Right now we book slot in `VaccinationSlotRepository` like that:

![image](https://user-images.githubusercontent.com/14038818/120903352-06dba380-c646-11eb-8c56-7d6e38a0fb57.png)

However, in some cases (when running multiple replicas serving a lot of concurrent users) this code might fail to book a slot even though there're still some slots available. That's due to race condition when the replicas would be trying to book the very same slot. Even though we try at least 5 times to book the slot in some cases that might not be enough, because all replicas will always select the same one (we want to keep the booking in blocks and don't want to book random slots).

There're multiple approaches how to do that -> we tried some code in `backend/src/test/kotlin/blue/mild/covid/vaxx/service/VaccinationSlotService.kt` but that didn't entirely work as expected (it was not better then the current implementation with mutex and multiple trials).

Note that we don't expect that much traffic and scaling, that would be able to cause this, so it we settled with the current implementation. However, this is an interesting engineering problem so feel free to submit PR that would solve our issue while running a lot of replicas and many concurrent users.

**Comment by LukasForst** [comment]
One of the easy solution might be for example adding a random delay (that increases with less attempts left) between these booking attempts - so different replicas would wait different time and then would be able to book the slots.

**Comment by skalahonza** [comment]
Offset by replica id 

Eg
Replica with id 1 takes first available 
Replica with id 2 take second available
Etc

**Comment by LukasForst** [comment]
We found solution, that seems to solve the problem directly in the PostgreSQL - see first use case and code snippet here - https://spin.atomicobject.com/2021/02/04/redis-postgresql/

```sql
BEGIN;

WITH job AS (
  SELECT
    id
  FROM
    jobs
  WHERE
    status = 'pending'
  LIMIT 1
  FOR UPDATE SKIP LOCKED
)
UPDATE
  jobs
SET
  status = 'running'
WHERE
  jobs.id = job.id
RETURNING
  jobs.*;

COMMIT;
```
