### ISSUE TITLE
Better data validation

### ISSUE THREAD

**Issue by tomaskourim** [mild-blue/covid-vaxx#271]
Na začátku dotazník nepožaduje rodné číslo
![image](https://user-images.githubusercontent.com/50045455/120936649-2d164780-c709-11eb-988e-27d0904bef2b.png)

Kdyz nasledne neco vyplnim, už to RC chce
![image](https://user-images.githubusercontent.com/50045455/120936735-af9f0700-c709-11eb-9d85-804b2ba1033a.png)

Kdyz pak opet smazu, rodne cislo stale chce
![image](https://user-images.githubusercontent.com/50045455/120936741-b9286f00-c709-11eb-8463-2ccfd2a7b9a4.png)

Dale v popisku nechceme `mestska cast`, ale proste jen `mesto`

Kdyz prekliknu na cizince, netrigruje se zmena tech poli, co po me jeste chce system
![image](https://user-images.githubusercontent.com/50045455/120936799-11f80780-c70a-11eb-99d3-3192260f1fc3.png)

**Comment by LukasForst** [comment]
![image](https://user-images.githubusercontent.com/14038818/120936904-c09c4800-c70a-11eb-985e-dacf76728169.png)
a ve warningu dole porad piseme "rodne cislo" ackoliv po cizincich chceme cislo pojistence
