### ISSUE TITLE
Technical info

### ISSUE THREAD

**Issue by tomaskourim** [mild-blue/covid-vaxx#285]
![image](https://user-images.githubusercontent.com/50045455/121139978-a44af900-c839-11eb-9d9b-73b8c3614c5b.png)
Sem pridat jeste mail ockovani@praha7.cz

Bud sem nebo do extra policka (piktogram počítače) bych pridal technicke informace:
`Podporované prohlížeče jsou (aktuální verze) Mozilla Firefox, Google Chrome a Safari. Naopak Internet Explorer není a nebude podporován a důzarně doporučujeme jej přestat používat obecně.`

`Projekt je vytvořen jako opensource a dostupný na Githubu (a href=https://github.com/mild-blue/covid-vaxx). Pokud máte technické dotazy, připomínky nebo se chcete dozvědět více o Mild Blue, kontaktujte nás na ockovani@mild.blue.`

**Comment by LukasForst** [comment]
a mozna vymenti `ockovani@mild.blue` za tenhle taky? protoze v soucasny chvili kdy zobrazime error tak je tam mail na nas, to je hloupe, neb my nejsme uplne ti, co maji opravovat spatne zadane udaje? @tomaskourim

**Comment by tomaskourim** [comment]
Jeste trochu jinak. Komunikoval bych to tak, že info je na ockovani@praha7.cz. Technické problémy na našem. Tzn. když to hodí error, nechal bych ten náš. Ale tady ten text o infolince bych přepsal na:
S dotazy ohledně očkování se můžete obrátit na infolinku Prahy 7, která je Vám k... ... nebo emailu ockovani@praha7.cz

Na konec, kde se zobrazí hláška o tom, že jestli mají chybu, ať napíšou mail, to bych změnil zas na praha7. A náš mail nechal u těch error hlášek.
