### ISSUE TITLE
Communication API

### ISSUE THREAD

**Issue by tomaskourim** [mild-blue/covid-vaxx#3]
Pripravit API, ktere propoji FE s BE a DB.

Uplne jednoduche, jeden endpoint. Ten z FE prijme data a odesle je do DB. Vrati 200 nebo chybu. 

Zatim uplne primitivne, postupne budeme pridavat ruzne validace dat a delat odpoved bohatsi.

**Comment by LukasForst** [comment]
API ready,nicmene je treba spojit FE a BE

**Comment by LukasForst** [comment]
tenhle task je tedy nakonec o poslani finalnich dat na BE, endpoint `POST ​/api​/patient`

https://covid-vaxx.stg.mild.blue/swagger-ui/index.html?url=/openapi.json#/default/post_api_patient
