### ISSUE TITLE
Smart personal number validation

### ISSUE THREAD

**Issue by tomaskourim** [mild-blue/covid-vaxx#43]
Chceme vyzadovat RC jako 10 (9) cisel bez lomitka nebo s, ale muzeme byt `smart` a odhalovat to.  Jak to bude psat, muzeme mu  rovnou pod rukama na frontendu opravit a lomitko pridat na spravne misto. A mozna me napadne jeste neco.

**Comment by marazt** [comment]
FE i BE akceptuje oboje s tim, ze do DB se to uklada bez. Osobne bych nic pod rukou neupravoval, pak ti to ustreli kurzor, ...

**Comment by LukasForst** [comment]
![image](https://user-images.githubusercontent.com/14038818/110129829-adef3b80-7dc8-11eb-86d4-7348d0e3e8ce.png)

kdyz je tam mezera navic, tak to nepusti uzivatele dal, asi by bylo chytrejsi to trimnout

**Comment by tomaskourim** [comment]
Možná ještě lépe. Rovnou tam mít kolonku na 6 čísel, pak `/` a pak kolonku na 4 (3) čísla. Pak je každému jasné, jak to má vyplnit. A když vyplní prvních 6 kurzor sám přeskočí za lomítko - mně osobně to přijde nejvíce user friendly.

A jinak samozřejmě mezeru trimovat. A obecně prostě omezit počet znaků co tam lze napsat.

**Comment by tomaskourim** [comment]
Jeste zde https://github.com/mild-blue/covid-vaxx/issues/202
