### ISSUE TITLE
Info page before actual step one

### ISSUE THREAD

**Issue by LukasForst** [mild-blue/covid-vaxx#50]
Stranka na ktery bude text ktery se casem doda 

plus tlacitko registrovat to presmeruje na formular.

Melo by vypadat

potrebujeme aby pak dobre fungovala captcha.

v komentari tomas doplni text

**Comment by kubantjan** [comment]
@misslecter rikala, ze to neni nutny delat pred #15, ze to zvladne i bez toho.

**Comment by LukasForst** [comment]
ok to pro me osobne neni problem, ale chtel bych hodit `api/question` a `api/insurance-company` za captcha auth taky - tzn predtim, nez se bude chtit FE zeptat na tyhle data, musi uz mit auth za sebou -- jak ho udela je asi na @misslecter, ja mel napad tenhle, ale je to sumak -- na to bude asi treba nastudovat, kdy presne ti google da tu captchu

reasoning za zamcenim tech dvou endpointu je minimalizovat pripadny ddos

**Comment by tomaskourim** [comment]
Infostranku chceme. Bude tam základní omáčka inforamcí od radnice či od nás, naše logo určitě atd. Pak tlačítko `registrovat`, které bude dělat captcha logiku co psal @LukasForst

**Comment by tomaskourim** [comment]
Text:

Registrační systém očkování.

Očkování proběhne ve Vaší volební místnosti. Datum a čas naleznete pomocí Vašeho příjmení ve Vaší schránce. Pro vstup do registračního systému pokračujte dále.

Tlačítko `Registrovat`
