### ISSUE TITLE
Page after successful registration

### ISSUE THREAD

**Issue by LukasForst** [mild-blue/covid-vaxx#51]
* chtelo by to posledni stranku po uspesne registraci
* na ni klidne muzou byt stale zobrazene ty zadane hodnoty, ale uz ne tlacitko odeslat
* stejne tak nebude mozne jit zpet pres ty taby
* pridat tlacitko "zacit znovu", ktere vymaze formulare a hodi uzivatele na prvni stranku -- use case je, kdyz jeden clovek registruje nekolik lidi najednou

**Comment by tomaskourim** [comment]
Znovu oteviram, stavajici chovani musime vylepsit, minimalne vymazat data z formulare a vratit se na prvni stranku/infostranku nebo tak neco.

**Comment by tomaskourim** [comment]
Udelame infostranku, kde bude shrnuti odeslanych informaci + nějaká omáčka informací od radnice.

**Comment by tomaskourim** [comment]
Zatim treba rikame, ze to bude to same jako v emailu, tedy:

Děkujeme za registraci k očkování. Dostavte se do Vaší volební místnosti ve stanovený čas. Den před očkování nepijte alkohol. Níže naleznete Vámi zadané údaje. V případě jakýchkoliv dotazů či připomínek se na nás neváhejte obrátit na info@mild.blue.
Za tým Mild Blue a Prahy 7
Tomáš Kouřim

A tady znovu shrnutí toho, co ten uživatel zadal.

**Comment by thangout** [comment]
![image](https://user-images.githubusercontent.com/11322384/110710700-a253a880-81fe-11eb-99ed-1d8650c6b86a.png)

**Comment by tomaskourim** [comment]
jo, vizualne za me gut - na kod se koukne nekdo povolanejsi ;)
