### ISSUE TITLE
Add insurance comp. numbers

### ISSUE THREAD

**Issue by tomaskourim** [mild-blue/covid-vaxx#62]
Mit hezci seznam zdravotnich pojistoven

![image](https://user-images.githubusercontent.com/50045455/110036443-4dff8300-7d3d-11eb-8e7f-f3f0c0e0e5f5.png)

Dal bych tam cely nazev a cislo ZP.

**Comment by LukasForst** [comment]
souvisi s #31 - v soucasny chvili BE posila zkratku + jmeno (viz [code](https://github.com/mild-blue/covid-vaxx/blob/master/backend/src/main/kotlin/blue/mild/covid/vaxx/dao/InsuranceCompany.kt)), pridat cislo neni problem

pridavam tag backend, abych na to myslel

**Comment by tomaskourim** [comment]
![image](https://user-images.githubusercontent.com/50045455/120785023-026f9780-c52d-11eb-826e-8d874dcf36fb.png)

Obecne chceme cislo, nazev a zkratku.

Dame vyssi prio
