### ISSUE TITLE
Idiot proof

### ISSUE THREAD

**Issue by tomaskourim** [mild-blue/covid-vaxx#64]
Muzeme nejak chytre bojovat proti ruznym extremnim situacim, treba jako 
![image](https://user-images.githubusercontent.com/50045455/110037718-185b9980-7d3f-11eb-99d7-d117f7eac36d.png)

**Comment by LukasForst** [comment]
> Programming today is a race between software engineers striving to build bigger and better idiot-proof programs, and the Universe trying to produce bigger and better idiots. So far, the Universe is winning.

Rick Cook, The Wizardry Compiled

anyway, BE dovoluje jmena/prijmeni az do velikosti 256 znaku, co bych spis delal je, ze FE osetrime tak, aby se nerozpadl presne pri tomhle

**Comment by tomaskourim** [comment]
Hele, to je sice pravda, ale proste trochu zamyslet bychom se nad tim meli. Nehori
