### ISSUE TITLE
Email validation

### ISSUE THREAD

**Issue by tomaskourim** [mild-blue/covid-vaxx#65]
Na FE projde email s@sw, ale na BE ne.
![image](https://user-images.githubusercontent.com/50045455/110088575-51bef400-7d95-11eb-8c60-f6eab3f86076.png)

Minimalne je potreba mit na FE a BE stejnou validaci, idealne pak i https://github.com/mild-blue/covid-vaxx/issues/63

**Comment by marazt** [comment]
Use same custom validator with same regex as on BE.

**Comment by tomaskourim** [comment]
![image](https://user-images.githubusercontent.com/50045455/110389258-90d69900-8064-11eb-928d-2aba6fc4366d.png)

Furt me to na FE pusti i s nevalidnim mailem, znovu oteviram.
