### ISSUE TITLE
Email service

### ISSUE THREAD

**Issue by tomaskourim** [mild-blue/covid-vaxx#73]
Po uspesnem odeslani formulare chceme poslat mail s temi vyplnenymi informacemi + nejaka omacka. Zvazit vlastni server (radnice muze pridat DNS), pripadne nejakou sluzbu (ideálně free nebo skoro free)

**Comment by LukasForst** [comment]
https://aws.amazon.com/ses/pricing/ - pokud bezime na amazonu, tak 62 000 mailu zdarma, tzn vezmeme tohle 

bude treba prozkoumat, jak to nahodit a jak poslat mail pres API

**Comment by LukasForst** [comment]
breakdown na mensi veci:
- [ ] pripravit terraform kterej nahodi AWS SES a usera, co ho muze pouzivat + nastavit spravne DNSka, aby se daly posilat maily z `mild.blue` domeny
- [ ] pripravit HTML template emailu - jak ma vypadat v cistym html + css a co ma obsahovat za informace
- [ ] service na BE, ktera vezme HTML template a narve do ni potrebna data (mimo jine se da pouzit primo kotlin a ktor, protoze maji templating na html) 
- [ ] service na BE, ktera vezme hotove HTML a zavola s nim AWS SES API a tim posle mail po uspesne registraci

**Comment by tomaskourim** [comment]
Ok, tak z toho uděláme nové tasky, ne? Ať k tomu může být PR vždycky

**Comment by LukasForst** [comment]
ok, rozpadnul jsem to do nekolika tasku, tuhle issue tedy zaviram
