### ISSUE TITLE
Save IP address of request

### ISSUE THREAD

**Issue by tomaskourim** [mild-blue/covid-vaxx#74]
Do DB si chceme ukládat i IP adresu, ze které nám data přišla. Více méně jenom pro evidenční účely a řešení případných problémů se zneužitím identity. Možná také na rozlišení, že se člověk hlásí z Prahy 7

**Comment by LukasForst** [comment]
implementacne reseno v #78, nicmene az pujdeme do produkce je treba spravne nastavit proxy, aby validovala headers a zabranila podvrhovani hlavicek - viz dokumentace
![image](https://user-images.githubusercontent.com/14038818/110177909-fc6efb00-7e05-11eb-816b-10d590c71bb9.png)

**Comment by tomaskourim** [comment]
Ok, tak z toho udeláš issue - validování headers?

**Comment by LukasForst** [comment]
jo, pridam dalsi issue
