### ISSUE TITLE
GDPR checkbox

### ISSUE THREAD

**Issue by tomaskourim** [mild-blue/covid-vaxx#76]
Před odeslání musí uživatel odshouhlasit i GDPR cosi (dodají). Také tam musí být dostupný celý text. Navrhuji tam mít funkcionalitu, že když člověk klikne na Smluvní podmínky (nebo tak něco), objeví se tam textbox s tím textem. Z nějakého GDPR důvodu je důležité, aby ten text byl na stejném místě jako klikátko.

**Comment by LukasForst** [comment]
- [ ] prevazne frontend
- [ ] na BE do DTO confirmations pridat tenhle souhlas

**Comment by tomaskourim** [comment]
Dobrý den,

Posílám text "Informace o zpracování osobních údajů"(*), který bude na stránce před odesláním. Teď tam jsou chceckboxy:
[ ] Potvrzuji ..
[ ] Souhlasím s aplikací ..

Nejlépe asi jako další checkbox:

[ ] Souhlasím se zpracováním osobních údajů

kde tučná část po kliknutí rozbalí/sbalí celý text (*).


S pozdravem,
Jiří Rošický


––– (*)
Informace o zpracování osobních údajů
Vaše osobní údaje: jméno, příjmení, rodné číslo, zdravotní pojišťovna, tel. číslo, email a zdravotní stav bude zpracovávat Správce za účelem: Očkování vakcínou proti covid-19. Právní základ zpracování je Váš souhlas. Nedochází k profilování. Dochází k automatizovanému zpracování. Zpracování bude ukončeno spolu s ukončením očkování. Údaje budou uchovávány po nezbytně nutnou dobu v souladu se zák. 499/2004 o archivnictví a spisové službě a dalšími relevantními právními předpisy.
Máte právo: odvolat svůj souhlas / na přístup k / na opravu / na výmaz / na omezení zpracování osobních údajů / podat stížnost u Úřadu pro ochranu osobních údajů / získat osobní údaje ve strukturovaném, strojově čitelném formátu.
Správce: Úřad MČ Praha 7, U Průhonu 1338/38, 1700 Praha 7. Pověřenec pro ochranu osobních údajů: dpo@praha7.cz, 604590908.
–––

**Comment by LukasForst** [comment]
FYI chybi zpracovani IP adresy, tu my ukladame a logujeme a podle https://www.fieldfisher.com/en/services/privacy-security-and-information/privacy-security-and-information-law-blog/can-a-dynamic-ip-address-constitute-personal-data je to osobni udaj 
![image](https://user-images.githubusercontent.com/14038818/110353170-09266580-8037-11eb-9184-1acd28fb027d.png)

@tomaskourim navrhuji pridat do toho zpracovani osobnich udaju, nebo odstranit z DB (a z logu...), ale to bych velice nerad

**Comment by misslecter** [comment]
@tomaskourim @LukasForst FE checkbox je přidaný, informace se posílá i na BE. Můžem tohle uzavřít nebo ještě necháme kvůli vylepšením na BE?

**Comment by LukasForst** [comment]
@misslecter predpokladam, ze je tohle spise otevrene kvuli te IP adrese, nebo @tomaskourim?

**Comment by tomaskourim** [comment]
@misslecter @LukasForst jeste toto https://github.com/mild-blue/covid-vaxx/pull/106
