### ISSUE TITLE
Email service - terraform to run AWS SES 

### ISSUE THREAD

**Issue by LukasForst** [mild-blue/covid-vaxx#80]
related #73

* pripravit terraform kterej nahodi AWS SES a usera, co ho muze pouzivat + nastavit spravne DNSka, aby se daly posilat maily z `mild.blue` domeny

https://aws.amazon.com/ses/

**Comment by LukasForst** [comment]
@tomaskourim z jake domeny chceme posilat maily? z nasi nebo z Prahy?

**Comment by tomaskourim** [comment]
> 
> 
> @tomaskourim z jake domeny chceme posilat maily? z nasi nebo z Prahy?

No, ja bych docela rad z naší. Ale asi je vhodnější z Prahy no :)

**Comment by kubantjan** [comment]
Nakonec service na mail jet pripravena, kod pridan, kterej posila emaily, jeste zbyva dodelat ty template html tasky.

Credentials na bitwardenu.

Testovat se to da lokalne v pohode ze clovek jde pres swagger ui a da tam svuj email..

Email je configurovatelnej, zatim default je services@mild.blue a vsechny mejly z domeny mild.blue jsou ok poslat. Jde tam pridat mejl libovolnej jinej staci jen ten konkretni mejl potvrdit..
