### ISSUE TITLE
Email service - BE service that takes final HTML and sends that to AWS SES API

### ISSUE THREAD

**Issue by LukasForst** [mild-blue/covid-vaxx#83]
related #73 

*  service na BE, ktera vezme hotove HTML a zavola s nim AWS SES API a tim posle mail po uspesne registraci

ukazka callu z javy https://docs.aws.amazon.com/ses/latest/DeveloperGuide/send-using-sdk-java.html

**Comment by kubantjan** [comment]
Tohle je done, uz je to cely ready, akorat chybi pridat ten template.
