### ISSUE TITLE
Enable rate limiting on the production proxy

### ISSUE THREAD

**Issue by LukasForst** [mild-blue/covid-vaxx#92]
* ted mame nejaky zakladni rate limiting primo na serveru
* ten by mel byt relativne benevolentni a slouzit pouze jako zachrana brzda
* proto predtim, nez pujdeme do produkce musime spravne nakonfigurovat reverse proxy aby limiting delala za nas
* v pripade treafiku https://doc.traefik.io/traefik/middlewares/ratelimit/
* v pripade Nginxu https://www.nginx.com/blog/rate-limiting-nginx/ anebo pak nejaky AWS produkt

**Comment by tomaskourim** [comment]
Jak tohle vypada? Myslel jsem, ze to uz je nejak vyreseno
