### ISSUE TITLE
Enforce unique personal numbers

### ISSUE THREAD

**Issue by kubantjan** [mild-blue/covid-vaxx#96]
Unikatnost rc - kdyz uz ho mame rict, tento uzivatel uz je registrovan. jestli chcete zmenit registraci kontaktujte nas na ....

unikatnost emailu asi nevyzadovat? Kdyz pribuzni registruji vsechny babicky, staci asi jeden email. Stejne tak teoreticky i telefon asi?

**Comment by LukasForst** [comment]
pro BE to neni problem, ale je treba v tomhle tasku i napsat nejakou testovaci service, ktera umi generovat rodna cisla, kvuli testovani - at uz kvuli performance testovani, tak i kvuli unit testum
